development:
  adapter: postgresql
  encoding: unicode
  database: sirihumor_development
  hostname: localhost

test: &test
  adapter: postgresql
  encoding: unicode
  database: sirihumor_test
  hostname: localhost
  
